<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net9.0</TargetFrameworks>
    <RootNamespace>SpmTool</RootNamespace>
    <AssemblyName>SpmTool</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="DX9toDX8.xslt" />
    <EmbeddedResource Include="XmlToSpm.xsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="FilterDX8.xslt" />
    <EmbeddedResource Include="DX8toDX9.xsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

</Project>
